import type { Question } from "./types";

// Reviewed against the linked sources on 2026-09-20. Difficulty is provisional.
export const QUESTIONS_KA: Question[] = [
  {
    id: "ka-geography-capital",
    level: 1,
    category: "გეოგრაფია",
    text: "რომელი ქალაქია საქართველოს დედაქალაქი?",
    answers: ["თბილისი", "ქუთაისი", "ბათუმი", "თელავი"],
    correctIndex: 0,
    explanation: "საქართველოს დედაქალაქია თბილისი.",
    sourceUrl: "https://georgia.travel/",
  },
  {
    id: "ka-space-sun",
    level: 2,
    category: "კოსმოსი",
    text: "რა ტიპის ციური სხეულია მზე?",
    answers: ["ვარსკვლავი", "პლანეტა", "კომეტა", "ბუნებრივი თანამგზავრი"],
    correctIndex: 0,
    explanation: "მზე ვარსკვლავია და ჩვენი მზის სისტემის ცენტრში მდებარეობს.",
    sourceUrl: "https://science.nasa.gov/sun/facts/",
  },
  {
    id: "ka-literature-rustaveli",
    level: 3,
    category: "ლიტერატურა",
    text: "ვინ არის „ვეფხისტყაოსნის“ ავტორი?",
    answers: ["შოთა რუსთაველი", "ილია ჭავჭავაძე", "აკაკი წერეთელი", "ვაჟა-ფშაველა"],
    correctIndex: 0,
    explanation: "„ვეფხისტყაოსანი“ შოთა რუსთაველის პოემაა.",
    sourceUrl: "https://georgia.travel/the-knight-in-the-panthers-skin",
  },
  {
    id: "ka-language-alphabet",
    level: 4,
    category: "ქართული ენა",
    text: "რამდენი ასოა თანამედროვე ქართულ ანბანში?",
    answers: ["33", "26", "32", "38"],
    correctIndex: 0,
    explanation:
      "თანამედროვე ქართული ანბანი 33 ასოს შეიცავს. ეს ასოები ბათუმის ანბანის კოშკზეც არის გამოსახული.",
    sourceUrl: "https://georgia.travel/family-attractions/batumis-miracle-park",
  },
  {
    id: "ka-space-mars",
    level: 5,
    category: "კოსმოსი",
    text: "რომელ პლანეტას უწოდებენ „წითელ პლანეტას“?",
    answers: ["მარსს", "ვენერას", "იუპიტერს", "ნეპტუნს"],
    correctIndex: 0,
    explanation:
      "მარსის ზედაპირზე არსებული რკინის მინერალების დაჟანგვა პლანეტას მოწითალო შეფერილობას აძლევს.",
    sourceUrl: "https://science.nasa.gov/mars/facts/",
  },
  {
    id: "ka-geography-pacific",
    level: 6,
    category: "გეოგრაფია",
    text: "რომელია დედამიწის უდიდესი ოკეანე?",
    answers: [
      "წყნარი ოკეანე",
      "ატლანტის ოკეანე",
      "ინდოეთის ოკეანე",
      "ჩრდილოეთის ყინულოვანი ოკეანე",
    ],
    correctIndex: 0,
    explanation: "წყნარი ოკეანე დედამიწის ყველაზე დიდი და ღრმა ოკეანეა.",
    sourceUrl: "https://oceanservice.noaa.gov/facts/biggestocean.html",
  },
  {
    id: "ka-chemistry-water",
    level: 7,
    category: "ქიმია",
    text: "რა არის წყლის ქიმიური ფორმულა?",
    answers: ["H₂O", "CO₂", "O₂", "NaCl"],
    correctIndex: 0,
    explanation: "წყლის მოლეკულა წყალბადის ორი ატომისა და ჟანგბადის ერთი ატომისგან შედგება.",
    sourceUrl: "https://www.usgs.gov/water-science-school/science/adhesion-and-cohesion-water",
  },
  {
    id: "ka-biology-heart",
    level: 8,
    category: "ბიოლოგია",
    text: "რამდენი კამერა აქვს ადამიანის გულს?",
    answers: ["ოთხი", "ორი", "სამი", "ექვსი"],
    correctIndex: 0,
    explanation: "გულს ოთხი კამერა აქვს: ორი წინაგული და ორი პარკუჭი.",
    sourceUrl: "https://www.nhlbi.nih.gov/health/heart/anatomy",
  },
  {
    id: "ka-chemistry-gold",
    level: 9,
    category: "ქიმია",
    text: "რომელი ქიმიური სიმბოლო აღნიშნავს ოქროს?",
    answers: ["Au", "Ag", "Fe", "Cu"],
    correctIndex: 0,
    explanation: "ოქროს ქიმიური სიმბოლოა Au, ხოლო მისი ატომური ნომერია 79.",
    sourceUrl: "https://periodic-table.rsc.org/element/79/",
  },
  {
    id: "ka-history-gelati",
    level: 10,
    category: "საქართველოს ისტორია",
    text: "რომელმა მეფემ დააარსა გელათის მონასტერი 1106 წელს?",
    answers: ["დავით IV აღმაშენებელმა", "თამარ მეფემ", "ვახტანგ გორგასალმა", "ერეკლე II-მ"],
    correctIndex: 0,
    explanation: "გელათის მონასტრის მშენებლობა 1106 წელს დავით IV აღმაშენებლის ბრძანებით დაიწყო.",
    sourceUrl: "https://whc.unesco.org/en/list/710",
  },
  {
    id: "ka-history-un",
    level: 11,
    category: "მსოფლიო ისტორია",
    text: "რომელ წელს დაარსდა ოფიციალურად გაერთიანებული ერების ორგანიზაცია?",
    answers: ["1945 წელს", "1919 წელს", "1939 წელს", "1955 წელს"],
    correctIndex: 0,
    explanation:
      "გაერო ოფიციალურად 1945 წლის 24 ოქტომბერს შეიქმნა, როდესაც მისი წესდება ძალაში შევიდა.",
    sourceUrl: "https://www.un.org/en/about-us/history-of-the-un",
  },
  {
    id: "ka-physics-ampere",
    level: 12,
    category: "ფიზიკა",
    text: "რა არის ელექტრული დენის ძალის საზომი ერთეული SI სისტემაში?",
    answers: ["ამპერი", "ვოლტი", "ომი", "ვატი"],
    correctIndex: 0,
    explanation: "ელექტრული დენის ძალის SI ერთეულია ამპერი, რომლის სიმბოლოა A.",
    sourceUrl: "https://www.bipm.org/en/si-base-units/ampere",
  },
  {
    id: "ka-space-ganymede",
    level: 13,
    category: "კოსმოსი",
    text: "რომელია მზის სისტემის უდიდესი ბუნებრივი თანამგზავრი?",
    answers: ["განიმედე", "ტიტანი", "ევროპა", "მთვარე"],
    correctIndex: 0,
    explanation:
      "იუპიტერის თანამგზავრი განიმედე მზის სისტემის უდიდესი თანამგზავრია; ზომით ის მერკურისაც აღემატება.",
    sourceUrl: "https://science.nasa.gov/jupiter/jupiter-moons/ganymede/facts/",
  },
  {
    id: "ka-literature-first-print",
    level: 14,
    category: "ლიტერატურა",
    text: "რომელ წელს დაიბეჭდა პირველად „ვეფხისტყაოსანი“?",
    answers: ["1712 წელს", "1629 წელს", "1801 წელს", "1887 წელს"],
    correctIndex: 0,
    explanation:
      "„ვეფხისტყაოსნის“ პირველი ბეჭდური გამოცემა 1712 წელს, ვახტანგ VI-ის დროს, თბილისში გამოვიდა.",
    sourceUrl: "https://georgia.travel/the-knight-in-the-panthers-skin",
  },
  {
    id: "ka-physics-neutron",
    level: 15,
    category: "ფიზიკა",
    text: "რომელმა მეცნიერმა აღმოაჩინა ნეიტრონი 1932 წელს?",
    answers: ["ჯეიმზ ჩედვიკმა", "ერნესტ რეზერფორდმა", "ჯოზეფ ჯონ ტომსონმა", "ნილს ბორმა"],
    correctIndex: 0,
    explanation:
      "ნეიტრონის აღმოჩენისთვის ჯეიმზ ჩედვიკს 1935 წელს ფიზიკის დარგში ნობელის პრემია მიენიჭა.",
    sourceUrl: "https://www.nobelprize.org/laureate/41",
  },
];
